// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BN_Astyle
{
    internal sealed partial class Vsix
    {
        public const string Id = "BN_Astyle.dadd8cc1-de8e-4283-a414-ff3f168328f4";
        public const string Name = "BN_Astyle";
        public const string Description = @"A simple Astyle 3.1 extension for vs2022.";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "Olanti";
        public const string Tags = "";
    }
}
